/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ABoolishValueBExpr2 extends PBExpr2
{
    private PBool _bool_;

    public ABoolishValueBExpr2()
    {
        // Constructor
    }

    public ABoolishValueBExpr2(
        @SuppressWarnings("hiding") PBool _bool_)
    {
        // Constructor
        setBool(_bool_);

    }

    @Override
    public Object clone()
    {
        return new ABoolishValueBExpr2(
            cloneNode(this._bool_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolishValueBExpr2(this);
    }

    public PBool getBool()
    {
        return this._bool_;
    }

    public void setBool(PBool node)
    {
        if(this._bool_ != null)
        {
            this._bool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bool_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bool_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bool_ == child)
        {
            this._bool_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bool_ == oldChild)
        {
            setBool((PBool) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
