/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AClosedWhileStatementAst extends PAst
{
    private PAst _exprTop_;
    private PAst _closedStatement_;

    public AClosedWhileStatementAst()
    {
        // Constructor
    }

    public AClosedWhileStatementAst(
        @SuppressWarnings("hiding") PAst _exprTop_,
        @SuppressWarnings("hiding") PAst _closedStatement_)
    {
        // Constructor
        setExprTop(_exprTop_);

        setClosedStatement(_closedStatement_);

    }

    @Override
    public Object clone()
    {
        return new AClosedWhileStatementAst(
            cloneNode(this._exprTop_),
            cloneNode(this._closedStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosedWhileStatementAst(this);
    }

    public PAst getExprTop()
    {
        return this._exprTop_;
    }

    public void setExprTop(PAst node)
    {
        if(this._exprTop_ != null)
        {
            this._exprTop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprTop_ = node;
    }

    public PAst getClosedStatement()
    {
        return this._closedStatement_;
    }

    public void setClosedStatement(PAst node)
    {
        if(this._closedStatement_ != null)
        {
            this._closedStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closedStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprTop_)
            + toString(this._closedStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprTop_ == child)
        {
            this._exprTop_ = null;
            return;
        }

        if(this._closedStatement_ == child)
        {
            this._closedStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprTop_ == oldChild)
        {
            setExprTop((PAst) newChild);
            return;
        }

        if(this._closedStatement_ == oldChild)
        {
            setClosedStatement((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
