/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AClosedStatement extends PStatement
{
    private PClosedStatement _closedStatement_;

    public AClosedStatement()
    {
        // Constructor
    }

    public AClosedStatement(
        @SuppressWarnings("hiding") PClosedStatement _closedStatement_)
    {
        // Constructor
        setClosedStatement(_closedStatement_);

    }

    @Override
    public Object clone()
    {
        return new AClosedStatement(
            cloneNode(this._closedStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosedStatement(this);
    }

    public PClosedStatement getClosedStatement()
    {
        return this._closedStatement_;
    }

    public void setClosedStatement(PClosedStatement node)
    {
        if(this._closedStatement_ != null)
        {
            this._closedStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closedStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._closedStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._closedStatement_ == child)
        {
            this._closedStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._closedStatement_ == oldChild)
        {
            setClosedStatement((PClosedStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
