/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AClosedIfStatement extends PClosedIfStatement
{
    private TIf _if_;
    private PExprTop _exprTop_;
    private TThen _then_;
    private PClosedStatement _do_;
    private TElse _else_;
    private PClosedStatement _doElse_;

    public AClosedIfStatement()
    {
        // Constructor
    }

    public AClosedIfStatement(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PExprTop _exprTop_,
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") PClosedStatement _do_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PClosedStatement _doElse_)
    {
        // Constructor
        setIf(_if_);

        setExprTop(_exprTop_);

        setThen(_then_);

        setDo(_do_);

        setElse(_else_);

        setDoElse(_doElse_);

    }

    @Override
    public Object clone()
    {
        return new AClosedIfStatement(
            cloneNode(this._if_),
            cloneNode(this._exprTop_),
            cloneNode(this._then_),
            cloneNode(this._do_),
            cloneNode(this._else_),
            cloneNode(this._doElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosedIfStatement(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PExprTop getExprTop()
    {
        return this._exprTop_;
    }

    public void setExprTop(PExprTop node)
    {
        if(this._exprTop_ != null)
        {
            this._exprTop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprTop_ = node;
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public PClosedStatement getDo()
    {
        return this._do_;
    }

    public void setDo(PClosedStatement node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PClosedStatement getDoElse()
    {
        return this._doElse_;
    }

    public void setDoElse(PClosedStatement node)
    {
        if(this._doElse_ != null)
        {
            this._doElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._exprTop_)
            + toString(this._then_)
            + toString(this._do_)
            + toString(this._else_)
            + toString(this._doElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._exprTop_ == child)
        {
            this._exprTop_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._doElse_ == child)
        {
            this._doElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._exprTop_ == oldChild)
        {
            setExprTop((PExprTop) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((PClosedStatement) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._doElse_ == oldChild)
        {
            setDoElse((PClosedStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
