/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AClosedIfStatementAst extends PAst
{
    private PAst _exprTop_;
    private PAst _do_;
    private PAst _else_;

    public AClosedIfStatementAst()
    {
        // Constructor
    }

    public AClosedIfStatementAst(
        @SuppressWarnings("hiding") PAst _exprTop_,
        @SuppressWarnings("hiding") PAst _do_,
        @SuppressWarnings("hiding") PAst _else_)
    {
        // Constructor
        setExprTop(_exprTop_);

        setDo(_do_);

        setElse(_else_);

    }

    @Override
    public Object clone()
    {
        return new AClosedIfStatementAst(
            cloneNode(this._exprTop_),
            cloneNode(this._do_),
            cloneNode(this._else_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosedIfStatementAst(this);
    }

    public PAst getExprTop()
    {
        return this._exprTop_;
    }

    public void setExprTop(PAst node)
    {
        if(this._exprTop_ != null)
        {
            this._exprTop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprTop_ = node;
    }

    public PAst getDo()
    {
        return this._do_;
    }

    public void setDo(PAst node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PAst getElse()
    {
        return this._else_;
    }

    public void setElse(PAst node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprTop_)
            + toString(this._do_)
            + toString(this._else_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprTop_ == child)
        {
            this._exprTop_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprTop_ == oldChild)
        {
            setExprTop((PAst) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((PAst) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
