/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationsAst extends PAst
{
    private PAst _identifier_;
    private PAst _type_;

    public ADeclarationsAst()
    {
        // Constructor
    }

    public ADeclarationsAst(
        @SuppressWarnings("hiding") PAst _identifier_,
        @SuppressWarnings("hiding") PAst _type_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setType(_type_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationsAst(
            cloneNode(this._identifier_),
            cloneNode(this._type_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationsAst(this);
    }

    public PAst getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(PAst node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PAst getType()
    {
        return this._type_;
    }

    public void setType(PAst node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._type_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((PAst) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
