/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyDeclarationsAst extends PAst
{

    public AEmptyDeclarationsAst()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyDeclarationsAst();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyDeclarationsAst(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
