/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AExprTopAst extends PAst
{
    private PAst _exprTop_;
    private PAst _expr_;

    public AExprTopAst()
    {
        // Constructor
    }

    public AExprTopAst(
        @SuppressWarnings("hiding") PAst _exprTop_,
        @SuppressWarnings("hiding") PAst _expr_)
    {
        // Constructor
        setExprTop(_exprTop_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AExprTopAst(
            cloneNode(this._exprTop_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprTopAst(this);
    }

    public PAst getExprTop()
    {
        return this._exprTop_;
    }

    public void setExprTop(PAst node)
    {
        if(this._exprTop_ != null)
        {
            this._exprTop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprTop_ = node;
    }

    public PAst getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PAst node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprTop_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprTop_ == child)
        {
            this._exprTop_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprTop_ == oldChild)
        {
            setExprTop((PAst) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
