/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseOpenStatement extends POpenStatement
{
    private PIfClosedElse _ifClosedElse_;
    private POpenStatement _openStatement_;

    public AIfElseOpenStatement()
    {
        // Constructor
    }

    public AIfElseOpenStatement(
        @SuppressWarnings("hiding") PIfClosedElse _ifClosedElse_,
        @SuppressWarnings("hiding") POpenStatement _openStatement_)
    {
        // Constructor
        setIfClosedElse(_ifClosedElse_);

        setOpenStatement(_openStatement_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseOpenStatement(
            cloneNode(this._ifClosedElse_),
            cloneNode(this._openStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseOpenStatement(this);
    }

    public PIfClosedElse getIfClosedElse()
    {
        return this._ifClosedElse_;
    }

    public void setIfClosedElse(PIfClosedElse node)
    {
        if(this._ifClosedElse_ != null)
        {
            this._ifClosedElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifClosedElse_ = node;
    }

    public POpenStatement getOpenStatement()
    {
        return this._openStatement_;
    }

    public void setOpenStatement(POpenStatement node)
    {
        if(this._openStatement_ != null)
        {
            this._openStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifClosedElse_)
            + toString(this._openStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifClosedElse_ == child)
        {
            this._ifClosedElse_ = null;
            return;
        }

        if(this._openStatement_ == child)
        {
            this._openStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifClosedElse_ == oldChild)
        {
            setIfClosedElse((PIfClosedElse) newChild);
            return;
        }

        if(this._openStatement_ == oldChild)
        {
            setOpenStatement((POpenStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
