/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AJustIfOpenStatement extends POpenStatement
{
    private PIfStatement _ifStatement_;
    private PStatementSequence _statementSequence_;

    public AJustIfOpenStatement()
    {
        // Constructor
    }

    public AJustIfOpenStatement(
        @SuppressWarnings("hiding") PIfStatement _ifStatement_,
        @SuppressWarnings("hiding") PStatementSequence _statementSequence_)
    {
        // Constructor
        setIfStatement(_ifStatement_);

        setStatementSequence(_statementSequence_);

    }

    @Override
    public Object clone()
    {
        return new AJustIfOpenStatement(
            cloneNode(this._ifStatement_),
            cloneNode(this._statementSequence_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJustIfOpenStatement(this);
    }

    public PIfStatement getIfStatement()
    {
        return this._ifStatement_;
    }

    public void setIfStatement(PIfStatement node)
    {
        if(this._ifStatement_ != null)
        {
            this._ifStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifStatement_ = node;
    }

    public PStatementSequence getStatementSequence()
    {
        return this._statementSequence_;
    }

    public void setStatementSequence(PStatementSequence node)
    {
        if(this._statementSequence_ != null)
        {
            this._statementSequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementSequence_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifStatement_)
            + toString(this._statementSequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifStatement_ == child)
        {
            this._ifStatement_ = null;
            return;
        }

        if(this._statementSequence_ == child)
        {
            this._statementSequence_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifStatement_ == oldChild)
        {
            setIfStatement((PIfStatement) newChild);
            return;
        }

        if(this._statementSequence_ == oldChild)
        {
            setStatementSequence((PStatementSequence) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
