/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ALessEqCompare extends PCompare
{
    private TLessEq _lessEq_;

    public ALessEqCompare()
    {
        // Constructor
    }

    public ALessEqCompare(
        @SuppressWarnings("hiding") TLessEq _lessEq_)
    {
        // Constructor
        setLessEq(_lessEq_);

    }

    @Override
    public Object clone()
    {
        return new ALessEqCompare(
            cloneNode(this._lessEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessEqCompare(this);
    }

    public TLessEq getLessEq()
    {
        return this._lessEq_;
    }

    public void setLessEq(TLessEq node)
    {
        if(this._lessEq_ != null)
        {
            this._lessEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessEq_ == child)
        {
            this._lessEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lessEq_ == oldChild)
        {
            setLessEq((TLessEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
