/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleStatementSequence extends PStatementSequence
{
    private PStatementSequence _statementSequence_;
    private TSemicolon _semicolon_;
    private PStatement _statement_;

    public AMultipleStatementSequence()
    {
        // Constructor
    }

    public AMultipleStatementSequence(
        @SuppressWarnings("hiding") PStatementSequence _statementSequence_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setStatementSequence(_statementSequence_);

        setSemicolon(_semicolon_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleStatementSequence(
            cloneNode(this._statementSequence_),
            cloneNode(this._semicolon_),
            cloneNode(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleStatementSequence(this);
    }

    public PStatementSequence getStatementSequence()
    {
        return this._statementSequence_;
    }

    public void setStatementSequence(PStatementSequence node)
    {
        if(this._statementSequence_ != null)
        {
            this._statementSequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementSequence_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statementSequence_)
            + toString(this._semicolon_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statementSequence_ == child)
        {
            this._statementSequence_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._statementSequence_ == oldChild)
        {
            setStatementSequence((PStatementSequence) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
