/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleVariablesDefinitionList extends PVariablesDefinitionList
{
    private PVariablesDefinitionList _variablesDefinitionList_;
    private PVariablesDefinition _variablesDefinition_;

    public AMultipleVariablesDefinitionList()
    {
        // Constructor
    }

    public AMultipleVariablesDefinitionList(
        @SuppressWarnings("hiding") PVariablesDefinitionList _variablesDefinitionList_,
        @SuppressWarnings("hiding") PVariablesDefinition _variablesDefinition_)
    {
        // Constructor
        setVariablesDefinitionList(_variablesDefinitionList_);

        setVariablesDefinition(_variablesDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleVariablesDefinitionList(
            cloneNode(this._variablesDefinitionList_),
            cloneNode(this._variablesDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleVariablesDefinitionList(this);
    }

    public PVariablesDefinitionList getVariablesDefinitionList()
    {
        return this._variablesDefinitionList_;
    }

    public void setVariablesDefinitionList(PVariablesDefinitionList node)
    {
        if(this._variablesDefinitionList_ != null)
        {
            this._variablesDefinitionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinitionList_ = node;
    }

    public PVariablesDefinition getVariablesDefinition()
    {
        return this._variablesDefinition_;
    }

    public void setVariablesDefinition(PVariablesDefinition node)
    {
        if(this._variablesDefinition_ != null)
        {
            this._variablesDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variablesDefinitionList_)
            + toString(this._variablesDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variablesDefinitionList_ == child)
        {
            this._variablesDefinitionList_ = null;
            return;
        }

        if(this._variablesDefinition_ == child)
        {
            this._variablesDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variablesDefinitionList_ == oldChild)
        {
            setVariablesDefinitionList((PVariablesDefinitionList) newChild);
            return;
        }

        if(this._variablesDefinition_ == oldChild)
        {
            setVariablesDefinition((PVariablesDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
