/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ANotBExpr extends PBExpr
{
    private TNot _not_;
    private PBExpr2 _bExpr2_;

    public ANotBExpr()
    {
        // Constructor
    }

    public ANotBExpr(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PBExpr2 _bExpr2_)
    {
        // Constructor
        setNot(_not_);

        setBExpr2(_bExpr2_);

    }

    @Override
    public Object clone()
    {
        return new ANotBExpr(
            cloneNode(this._not_),
            cloneNode(this._bExpr2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotBExpr(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PBExpr2 getBExpr2()
    {
        return this._bExpr2_;
    }

    public void setBExpr2(PBExpr2 node)
    {
        if(this._bExpr2_ != null)
        {
            this._bExpr2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bExpr2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._bExpr2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._bExpr2_ == child)
        {
            this._bExpr2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._bExpr2_ == oldChild)
        {
            setBExpr2((PBExpr2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
