/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AOpenWhileOpenStatement extends POpenStatement
{
    private POpenWhileStatement _openWhileStatement_;

    public AOpenWhileOpenStatement()
    {
        // Constructor
    }

    public AOpenWhileOpenStatement(
        @SuppressWarnings("hiding") POpenWhileStatement _openWhileStatement_)
    {
        // Constructor
        setOpenWhileStatement(_openWhileStatement_);

    }

    @Override
    public Object clone()
    {
        return new AOpenWhileOpenStatement(
            cloneNode(this._openWhileStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpenWhileOpenStatement(this);
    }

    public POpenWhileStatement getOpenWhileStatement()
    {
        return this._openWhileStatement_;
    }

    public void setOpenWhileStatement(POpenWhileStatement node)
    {
        if(this._openWhileStatement_ != null)
        {
            this._openWhileStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openWhileStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._openWhileStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._openWhileStatement_ == child)
        {
            this._openWhileStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._openWhileStatement_ == oldChild)
        {
            setOpenWhileStatement((POpenWhileStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
