/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AOpenStatement extends PStatement
{
    private POpenStatement _openStatement_;

    public AOpenStatement()
    {
        // Constructor
    }

    public AOpenStatement(
        @SuppressWarnings("hiding") POpenStatement _openStatement_)
    {
        // Constructor
        setOpenStatement(_openStatement_);

    }

    @Override
    public Object clone()
    {
        return new AOpenStatement(
            cloneNode(this._openStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpenStatement(this);
    }

    public POpenStatement getOpenStatement()
    {
        return this._openStatement_;
    }

    public void setOpenStatement(POpenStatement node)
    {
        if(this._openStatement_ != null)
        {
            this._openStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._openStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._openStatement_ == child)
        {
            this._openStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._openStatement_ == oldChild)
        {
            setOpenStatement((POpenStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
