/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AOrAst extends PAst
{
    private PAst _expr_;
    private PAst _factor_;

    public AOrAst()
    {
        // Constructor
    }

    public AOrAst(
        @SuppressWarnings("hiding") PAst _expr_,
        @SuppressWarnings("hiding") PAst _factor_)
    {
        // Constructor
        setExpr(_expr_);

        setFactor(_factor_);

    }

    @Override
    public Object clone()
    {
        return new AOrAst(
            cloneNode(this._expr_),
            cloneNode(this._factor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrAst(this);
    }

    public PAst getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PAst node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PAst getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PAst node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._factor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PAst) newChild);
            return;
        }

        if(this._factor_ == oldChild)
        {
            setFactor((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
