/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AProgramStart extends PProgramStart
{
    private PProgramHeader _programHeader_;
    private PDeclarations _declarations_;
    private PBody _body_;
    private TDot _dot_;

    public AProgramStart()
    {
        // Constructor
    }

    public AProgramStart(
        @SuppressWarnings("hiding") PProgramHeader _programHeader_,
        @SuppressWarnings("hiding") PDeclarations _declarations_,
        @SuppressWarnings("hiding") PBody _body_,
        @SuppressWarnings("hiding") TDot _dot_)
    {
        // Constructor
        setProgramHeader(_programHeader_);

        setDeclarations(_declarations_);

        setBody(_body_);

        setDot(_dot_);

    }

    @Override
    public Object clone()
    {
        return new AProgramStart(
            cloneNode(this._programHeader_),
            cloneNode(this._declarations_),
            cloneNode(this._body_),
            cloneNode(this._dot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramStart(this);
    }

    public PProgramHeader getProgramHeader()
    {
        return this._programHeader_;
    }

    public void setProgramHeader(PProgramHeader node)
    {
        if(this._programHeader_ != null)
        {
            this._programHeader_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programHeader_ = node;
    }

    public PDeclarations getDeclarations()
    {
        return this._declarations_;
    }

    public void setDeclarations(PDeclarations node)
    {
        if(this._declarations_ != null)
        {
            this._declarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarations_ = node;
    }

    public PBody getBody()
    {
        return this._body_;
    }

    public void setBody(PBody node)
    {
        if(this._body_ != null)
        {
            this._body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._body_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programHeader_)
            + toString(this._declarations_)
            + toString(this._body_)
            + toString(this._dot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programHeader_ == child)
        {
            this._programHeader_ = null;
            return;
        }

        if(this._declarations_ == child)
        {
            this._declarations_ = null;
            return;
        }

        if(this._body_ == child)
        {
            this._body_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programHeader_ == oldChild)
        {
            setProgramHeader((PProgramHeader) newChild);
            return;
        }

        if(this._declarations_ == oldChild)
        {
            setDeclarations((PDeclarations) newChild);
            return;
        }

        if(this._body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
