/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleClosedStatement extends PClosedStatement
{
    private PSimpleStatement _simpleStatement_;

    public ASimpleClosedStatement()
    {
        // Constructor
    }

    public ASimpleClosedStatement(
        @SuppressWarnings("hiding") PSimpleStatement _simpleStatement_)
    {
        // Constructor
        setSimpleStatement(_simpleStatement_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleClosedStatement(
            cloneNode(this._simpleStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleClosedStatement(this);
    }

    public PSimpleStatement getSimpleStatement()
    {
        return this._simpleStatement_;
    }

    public void setSimpleStatement(PSimpleStatement node)
    {
        if(this._simpleStatement_ != null)
        {
            this._simpleStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleStatement_ == child)
        {
            this._simpleStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleStatement_ == oldChild)
        {
            setSimpleStatement((PSimpleStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
