/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class ASingleVariablesDefinitionList extends PVariablesDefinitionList
{
    private PVariablesDefinition _variablesDefinition_;

    public ASingleVariablesDefinitionList()
    {
        // Constructor
    }

    public ASingleVariablesDefinitionList(
        @SuppressWarnings("hiding") PVariablesDefinition _variablesDefinition_)
    {
        // Constructor
        setVariablesDefinition(_variablesDefinition_);

    }

    @Override
    public Object clone()
    {
        return new ASingleVariablesDefinitionList(
            cloneNode(this._variablesDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleVariablesDefinitionList(this);
    }

    public PVariablesDefinition getVariablesDefinition()
    {
        return this._variablesDefinition_;
    }

    public void setVariablesDefinition(PVariablesDefinition node)
    {
        if(this._variablesDefinition_ != null)
        {
            this._variablesDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variablesDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variablesDefinition_ == child)
        {
            this._variablesDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variablesDefinition_ == oldChild)
        {
            setVariablesDefinition((PVariablesDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
