/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AStatementSequenceAst extends PAst
{
    private PAst _statementSequence_;
    private PAst _statement_;

    public AStatementSequenceAst()
    {
        // Constructor
    }

    public AStatementSequenceAst(
        @SuppressWarnings("hiding") PAst _statementSequence_,
        @SuppressWarnings("hiding") PAst _statement_)
    {
        // Constructor
        setStatementSequence(_statementSequence_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AStatementSequenceAst(
            cloneNode(this._statementSequence_),
            cloneNode(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementSequenceAst(this);
    }

    public PAst getStatementSequence()
    {
        return this._statementSequence_;
    }

    public void setStatementSequence(PAst node)
    {
        if(this._statementSequence_ != null)
        {
            this._statementSequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementSequence_ = node;
    }

    public PAst getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PAst node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statementSequence_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statementSequence_ == child)
        {
            this._statementSequence_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._statementSequence_ == oldChild)
        {
            setStatementSequence((PAst) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
