/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AVariablesDefinitionListAst extends PAst
{
    private PAst _variablesDefinitionList_;
    private PAst _variablesDefinition_;

    public AVariablesDefinitionListAst()
    {
        // Constructor
    }

    public AVariablesDefinitionListAst(
        @SuppressWarnings("hiding") PAst _variablesDefinitionList_,
        @SuppressWarnings("hiding") PAst _variablesDefinition_)
    {
        // Constructor
        setVariablesDefinitionList(_variablesDefinitionList_);

        setVariablesDefinition(_variablesDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AVariablesDefinitionListAst(
            cloneNode(this._variablesDefinitionList_),
            cloneNode(this._variablesDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariablesDefinitionListAst(this);
    }

    public PAst getVariablesDefinitionList()
    {
        return this._variablesDefinitionList_;
    }

    public void setVariablesDefinitionList(PAst node)
    {
        if(this._variablesDefinitionList_ != null)
        {
            this._variablesDefinitionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinitionList_ = node;
    }

    public PAst getVariablesDefinition()
    {
        return this._variablesDefinition_;
    }

    public void setVariablesDefinition(PAst node)
    {
        if(this._variablesDefinition_ != null)
        {
            this._variablesDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variablesDefinitionList_)
            + toString(this._variablesDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variablesDefinitionList_ == child)
        {
            this._variablesDefinitionList_ = null;
            return;
        }

        if(this._variablesDefinition_ == child)
        {
            this._variablesDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variablesDefinitionList_ == oldChild)
        {
            setVariablesDefinitionList((PAst) newChild);
            return;
        }

        if(this._variablesDefinition_ == oldChild)
        {
            setVariablesDefinition((PAst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
