/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AVariablesDeclaration extends PVariablesDeclaration
{
    private TVar _var_;
    private PVariablesDefinitionList _variablesDefinitionList_;

    public AVariablesDeclaration()
    {
        // Constructor
    }

    public AVariablesDeclaration(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") PVariablesDefinitionList _variablesDefinitionList_)
    {
        // Constructor
        setVar(_var_);

        setVariablesDefinitionList(_variablesDefinitionList_);

    }

    @Override
    public Object clone()
    {
        return new AVariablesDeclaration(
            cloneNode(this._var_),
            cloneNode(this._variablesDefinitionList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariablesDeclaration(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PVariablesDefinitionList getVariablesDefinitionList()
    {
        return this._variablesDefinitionList_;
    }

    public void setVariablesDefinitionList(PVariablesDefinitionList node)
    {
        if(this._variablesDefinitionList_ != null)
        {
            this._variablesDefinitionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinitionList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._variablesDefinitionList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._variablesDefinitionList_ == child)
        {
            this._variablesDefinitionList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._variablesDefinitionList_ == oldChild)
        {
            setVariablesDefinitionList((PVariablesDefinitionList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
