/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.node;

import pascal.analysis.*;

@SuppressWarnings("nls")
public final class AWhileOOpenWhileStatement extends POpenWhileStatement
{
    private TWhile _while_;
    private PExprTop _exprTop_;
    private TDo _do_;
    private POpenStatement _openStatement_;

    public AWhileOOpenWhileStatement()
    {
        // Constructor
    }

    public AWhileOOpenWhileStatement(
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") PExprTop _exprTop_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") POpenStatement _openStatement_)
    {
        // Constructor
        setWhile(_while_);

        setExprTop(_exprTop_);

        setDo(_do_);

        setOpenStatement(_openStatement_);

    }

    @Override
    public Object clone()
    {
        return new AWhileOOpenWhileStatement(
            cloneNode(this._while_),
            cloneNode(this._exprTop_),
            cloneNode(this._do_),
            cloneNode(this._openStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileOOpenWhileStatement(this);
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public PExprTop getExprTop()
    {
        return this._exprTop_;
    }

    public void setExprTop(PExprTop node)
    {
        if(this._exprTop_ != null)
        {
            this._exprTop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprTop_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public POpenStatement getOpenStatement()
    {
        return this._openStatement_;
    }

    public void setOpenStatement(POpenStatement node)
    {
        if(this._openStatement_ != null)
        {
            this._openStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._while_)
            + toString(this._exprTop_)
            + toString(this._do_)
            + toString(this._openStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._exprTop_ == child)
        {
            this._exprTop_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._openStatement_ == child)
        {
            this._openStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._exprTop_ == oldChild)
        {
            setExprTop((PExprTop) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._openStatement_ == oldChild)
        {
            setOpenStatement((POpenStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
