/* This file was generated by SableCC (http://www.sablecc.org/). */

package pascal.lexer;

import java.io.*;
import pascal.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBegin(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProgram(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWriteln(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBreak(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqual(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLess(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreater(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessEq(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterEq(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnequal(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhitespace(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {37, 37, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {48, 57, 13}, {58, 58, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 65, 19}, {66, 66, 20}, {67, 67, 21}, {68, 68, 22}, {69, 69, 23}, {70, 70, 24}, {71, 72, 21}, {73, 73, 25}, {74, 77, 21}, {78, 78, 26}, {79, 79, 27}, {80, 80, 28}, {81, 83, 21}, {84, 84, 29}, {85, 85, 21}, {86, 86, 30}, {87, 87, 31}, {88, 88, 32}, {89, 90, 21}, {97, 97, 19}, {98, 98, 20}, {99, 99, 21}, {100, 100, 22}, {101, 101, 23}, {102, 102, 24}, {103, 104, 21}, {105, 105, 25}, {106, 109, 21}, {110, 110, 26}, {111, 111, 27}, {112, 112, 28}, {113, 115, 21}, {116, 116, 29}, {117, 117, 21}, {118, 118, 30}, {119, 119, 31}, {120, 120, 32}, {121, 122, 21}, {123, 123, 33}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 13}, },
            {{61, 61, 34}, },
            {},
            {{61, 61, 35}, {62, 62, 36}, },
            {},
            {{61, 61, 37}, },
            {{48, 57, 38}, {65, 77, 39}, {78, 78, 40}, {79, 90, 39}, {97, 109, 39}, {110, 110, 40}, {111, 122, 39}, },
            {{48, 57, 38}, {65, 68, 39}, {69, 69, 41}, {70, 78, 39}, {79, 79, 42}, {80, 81, 39}, {82, 82, 43}, {83, 90, 39}, {97, 100, 39}, {101, 101, 41}, {102, 110, 39}, {111, 111, 42}, {112, 113, 39}, {114, 114, 43}, {115, 122, 39}, },
            {{48, 57, 38}, {65, 90, 39}, {97, 122, 39}, },
            {{48, 57, 38}, {65, 72, 39}, {73, 73, 44}, {74, 78, 39}, {79, 79, 45}, {80, 90, 39}, {97, 104, 39}, {105, 105, 44}, {106, 110, 39}, {111, 111, 45}, {112, 122, 39}, },
            {{48, 57, 38}, {65, 75, 39}, {76, 76, 46}, {77, 77, 39}, {78, 78, 47}, {79, 90, 39}, {97, 107, 39}, {108, 108, 46}, {109, 109, 39}, {110, 110, 47}, {111, 122, 39}, },
            {{48, 57, 38}, {65, 65, 48}, {66, 90, 39}, {97, 97, 48}, {98, 122, 39}, },
            {{48, 57, 38}, {65, 69, 39}, {70, 70, 49}, {71, 77, 39}, {78, 78, 50}, {79, 90, 39}, {97, 101, 39}, {102, 102, 49}, {103, 109, 39}, {110, 110, 50}, {111, 122, 39}, },
            {{48, 57, 38}, {65, 78, 39}, {79, 79, 51}, {80, 90, 39}, {97, 110, 39}, {111, 111, 51}, {112, 122, 39}, },
            {{48, 57, 38}, {65, 81, 39}, {82, 82, 52}, {83, 90, 39}, {97, 113, 39}, {114, 114, 52}, {115, 122, 39}, },
            {{48, 81, -29}, {82, 82, 53}, {83, 113, -29}, {114, 114, 53}, {115, 122, 39}, },
            {{48, 57, 38}, {65, 71, 39}, {72, 72, 54}, {73, 81, 39}, {82, 82, 55}, {83, 90, 39}, {97, 103, 39}, {104, 104, 54}, {105, 113, 39}, {114, 114, 55}, {115, 122, 39}, },
            {{48, 57, 38}, {65, 65, 56}, {66, 90, 39}, {97, 97, 56}, {98, 122, 39}, },
            {{48, 71, -31}, {72, 72, 57}, {73, 81, 39}, {82, 82, 58}, {83, 103, -31}, {104, 104, 57}, {105, 113, 39}, {114, 114, 58}, {115, 122, 39}, },
            {{48, 78, -28}, {79, 79, 59}, {80, 110, -28}, {111, 111, 59}, {112, 122, 39}, },
            {{32, 122, 60}, {124, 124, 60}, {125, 125, 61}, {126, 127, 60}, },
            {},
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 57, 38}, {65, 67, 39}, {68, 68, 62}, {69, 90, 39}, {97, 99, 39}, {100, 100, 62}, {101, 122, 39}, },
            {{48, 57, 38}, {65, 70, 39}, {71, 71, 63}, {72, 90, 39}, {97, 102, 39}, {103, 103, 63}, {104, 122, 39}, },
            {{48, 78, -28}, {79, 79, 64}, {80, 110, -28}, {111, 111, 64}, {112, 122, 39}, },
            {{48, 68, -22}, {69, 69, 65}, {70, 90, 39}, {97, 100, 39}, {101, 101, 65}, {102, 122, 39}, },
            {{48, 57, 38}, {65, 85, 39}, {86, 86, 66}, {87, 90, 39}, {97, 117, 39}, {118, 118, 66}, {119, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 57, 38}, {65, 82, 39}, {83, 83, 67}, {84, 90, 39}, {97, 114, 39}, {115, 115, 67}, {116, 122, 39}, },
            {{48, 67, -42}, {68, 68, 68}, {69, 99, -42}, {100, 100, 68}, {101, 122, 39}, },
            {{48, 75, -25}, {76, 76, 69}, {77, 90, 39}, {97, 107, 39}, {108, 108, 69}, {109, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 57, 38}, {65, 83, 39}, {84, 84, 70}, {85, 90, 39}, {97, 115, 39}, {116, 116, 70}, {117, 122, 39}, },
            {{48, 83, -52}, {84, 84, 71}, {85, 115, -52}, {116, 116, 71}, {117, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 78, -28}, {79, 79, 72}, {80, 110, -28}, {111, 111, 72}, {112, 122, 39}, },
            {{48, 68, -22}, {69, 69, 73}, {70, 100, -45}, {101, 101, 73}, {102, 122, 39}, },
            {{48, 57, 38}, {65, 84, 39}, {85, 85, 74}, {86, 90, 39}, {97, 116, 39}, {117, 117, 74}, {118, 122, 39}, },
            {{48, 81, -29}, {82, 82, 75}, {83, 113, -29}, {114, 114, 75}, {115, 122, 39}, },
            {{48, 72, -24}, {73, 73, 76}, {74, 90, 39}, {97, 104, 39}, {105, 105, 76}, {106, 122, 39}, },
            {{48, 72, -24}, {73, 73, 77}, {74, 104, -59}, {105, 105, 77}, {106, 122, 39}, },
            {{48, 81, -29}, {82, 82, 78}, {83, 113, -29}, {114, 114, 78}, {115, 122, 39}, },
            {{32, 127, -35}, },
            {},
            {{48, 122, -23}, },
            {{48, 72, -24}, {73, 73, 79}, {74, 104, -59}, {105, 105, 79}, {106, 122, 39}, },
            {{48, 75, -25}, {76, 76, 80}, {77, 107, -50}, {108, 108, 80}, {109, 122, 39}, },
            {{48, 57, 38}, {65, 65, 81}, {66, 90, 39}, {97, 97, 81}, {98, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 68, -22}, {69, 69, 82}, {70, 100, -45}, {101, 101, 82}, {102, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 82, -48}, {83, 83, 83}, {84, 114, -48}, {115, 115, 83}, {116, 122, 39}, },
            {{48, 68, -22}, {69, 69, 84}, {70, 100, -45}, {101, 101, 84}, {102, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 70, -43}, {71, 71, 85}, {72, 102, -43}, {103, 103, 85}, {104, 122, 39}, },
            {{48, 77, -21}, {78, 78, 86}, {79, 109, -21}, {110, 110, 86}, {111, 122, 39}, },
            {{48, 68, -22}, {69, 69, 87}, {70, 100, -45}, {101, 101, 87}, {102, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 75, -25}, {76, 76, 88}, {77, 107, -50}, {108, 108, 88}, {109, 122, 39}, },
            {{48, 83, -52}, {84, 84, 89}, {85, 115, -52}, {116, 116, 89}, {117, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 77, -21}, {78, 78, 90}, {79, 109, -21}, {110, 110, 90}, {111, 122, 39}, },
            {{48, 68, -22}, {69, 69, 91}, {70, 100, -45}, {101, 101, 91}, {102, 122, 39}, },
            {{48, 57, 38}, {65, 74, 39}, {75, 75, 92}, {76, 90, 39}, {97, 106, 39}, {107, 107, 92}, {108, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 68, -22}, {69, 69, 93}, {70, 100, -45}, {101, 101, 93}, {102, 122, 39}, },
            {{48, 70, -43}, {71, 71, 94}, {72, 102, -43}, {103, 103, 94}, {104, 122, 39}, },
            {{48, 81, -29}, {82, 82, 95}, {83, 113, -29}, {114, 114, 95}, {115, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 68, -22}, {69, 69, 96}, {70, 100, -45}, {101, 101, 96}, {102, 122, 39}, },
            {{48, 68, -22}, {69, 69, 97}, {70, 100, -45}, {101, 101, 97}, {102, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 57, 38}, {65, 65, 98}, {66, 90, 39}, {97, 97, 98}, {98, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 68, -22}, {69, 69, 99}, {70, 100, -45}, {101, 101, 99}, {102, 122, 39}, },
            {{48, 57, 38}, {65, 65, 100}, {66, 90, 39}, {97, 97, 100}, {98, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 75, -25}, {76, 76, 101}, {77, 107, -50}, {108, 108, 101}, {109, 122, 39}, },
            {{48, 77, -21}, {78, 78, 102}, {79, 109, -21}, {110, 110, 102}, {111, 122, 39}, },
            {{48, 81, -29}, {82, 82, 103}, {83, 113, -29}, {114, 114, 103}, {115, 122, 39}, },
            {{48, 57, 38}, {65, 76, 39}, {77, 77, 104}, {78, 90, 39}, {97, 108, 39}, {109, 109, 104}, {110, 122, 39}, },
            {{48, 77, -21}, {78, 78, 105}, {79, 109, -21}, {110, 110, 105}, {111, 122, 39}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 40, 40, 40, 40, 23, 35, 36, 22, 20, 31, 21, 34, 38, 32, 33, 26, 25, 27, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, -1, 24, 28, 30, 29, 37, 37, 37, 37, 37, 37, 37, 13, 37, 37, 37, 10, 37, 37, 17, 37, 37, 37, 37, 37, 37, 37, -1, 39, 16, 37, 37, 37, 1, 37, 0, 37, 37, 19, 37, 37, 37, 2, 37, 37, 18, 37, 37, 37, 15, 37, 37, 37, 14, 8, 37, 37, 3, 37, 12, 9, 37, 37, 11, 37, 37, 37, 37, 37, 7, 6, 4, 5, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
